-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 14:40:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ProejetoIntegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ProejetoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ProejetoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `db_ProejetoIntegrador` ;

-- -----------------------------------------------------
-- Table `db_ProejetoIntegrador`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProejetoIntegrador`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_ProejetoIntegrador`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProejetoIntegrador`.`tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_ProejetoIntegrador`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProejetoIntegrador`.`postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NULL,
  `conteudo` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  `tema_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagem_tema_idx` (`tema_id` ASC) VISIBLE,
  INDEX `fk_postagem_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_tema`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_ProejetoIntegrador`.`tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ProejetoIntegrador`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
